name: Pull Request Validation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Vérifier que les fichiers Terraform sont valides
    - name: Validate Terraform Files
      run: |
        terraform init
        terraform validate

    # Construire l'image Docker pour vérifier qu'elle est correcte
    - name: Login to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t guayben/shop-app-pr ./api

    # (Optionnel) Ajouter des tests unitaires ou d'intégration
    - name: Run Python Unit Tests
      run: |
        pip install -r requirements.txt
        pytest
